name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU # QEMU is used to create a virtual machine for the build process (required for multi-architecture images)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx # Docker Buildx is used to build multi-architecture images
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todobedo:latest
          platforms: linux/amd64,linux/arm64
  
  deploy:
    needs: [build-and-push]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy Docker Compose & Script to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }} # IP of the server (get from the server provider e.g. digitalocean)
          username: ${{ secrets.SSH_USER }} # root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'docker/docker-compose.yaml,scripts/deploy.sh' #IMPORTANT: make sure docker, and scripts folder is present in your VPS
          target: '/root'
    
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: sh /root/scripts/deploy.sh
